on:
  push:
    tags:
      - 'v*'

name: "Publish Docker Image"

env:
  SLUG_DOCKERHUB: ${{ secrets.DOCKER_USERNAME }}/gloomhavensecretary
  SLUG_GHCR: ghcr.io/${{ github.repository_owner }}/gloomhavensecretary

jobs:
  build-and-publish-docker-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      -
        name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.SLUG_DOCKERHUB }}
            ${{ env.SLUG_GHCR }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # automatic: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Inspect image
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.SLUG_DOCKERHUB }}:${{ steps.meta.outputs.version }}
          docker image inspect ${{ env.SLUG_DOCKERHUB }}:${{ steps.meta.outputs.version }}
          docker pull ${{ env.SLUG_GHCR }}:${{ steps.meta.outputs.version }}
          docker image inspect ${{ env.SLUG_GHCR }}:${{ steps.meta.outputs.version }}
